name: 'Build'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        uses: ./
        id: test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          documentation_paths: |
            test
          backend_paths: |
            test
          frontend_paths: |
            test
      - name: Echo plugin output
        run: | 
          echo "test_environment: ${{ steps.test.outputs.test_environment }}"
          echo "frontend_tasks: ${{ steps.test.outputs.frontend_tasks }}"
          echo "documentation_tasks: ${{ steps.test.outputs.documentation_tasks }}"
          echo "backend_tasks: ${{ steps.test.outputs.backend_tasks }}"
